import { UILayer } from "~/types";

export const LAYER_BLOCKS: UILayer[] = [
  {
    id: "linear",
    label: "Linear",
    color: "#20FF8F",
    activationFunction: "ReLU",
    inputNeurons: 8,
    outputNeurons: 8,
  },
  {
    id: "conv1D",
    label: "Conv1D",
    color: "#FFD620",
    activationFunction: "ReLU",
    inputNeurons: 8,
    outputNeurons: 8,
    otherParams: { kernelSize: 3, stride: 1, padding: 0 },
  },
  {
    id: "conv2D",
    label: "Conv2D",
    color: "#FFD620",
    activationFunction: "ReLU",
    inputNeurons: 8,
    outputNeurons: 8,
    otherParams: { kernelSize: 3, stride: 1, padding: 1 },
  },
  {
    id: "conv3D",
    label: "Conv3D",
    color: "#FFD620",
    activationFunction: "ReLU",
    inputNeurons: 8,
    outputNeurons: 8,
    otherParams: { kernelSize: 3, stride: 1, padding: 0, dilation: 1 },
  },
  {
    id: "rnn",
    label: "RNN",
    color: "#FF8C20",
    activationFunction: "ReLU",
    inputNeurons: 8,
    outputNeurons: 8,
    otherParams: { hiddenSize: 32, dropout: 0.1 },
  },
  {
    id: "gru",
    label: "GRU",
    color: "#FF4920",
    activationFunction: "ReLU",
    inputNeurons: 8,
    outputNeurons: 8,
    otherParams: { hiddenSize: 32, dropout: 0.2 },
  },
  {
    id: "flatten",
    label: "Flatten",
    color: "#FF208F",
    activationFunction: "",
    inputNeurons: 8,
    outputNeurons: 8,
  },
];
